export default {
  UPDATE_EMAIL: 'UPDATE_EMAIL',

  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',

  UPTATE_CURRENTLY_EDITED_TODO_INDEX: 'UPTATE_CURRENTLY_EDITED_TODO_INDEX',
  UPDATE_LOGGING_IN_FLAG: 'UPDATE_LOGGING_IN_FLAG',
}