export default {
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',

  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',

  UPDATE_LOGGING_IN_FLAG: 'UPDATE_LOGGING_IN_FLAG',
  UPDATE_REGISTERING_FLAG: 'UPDATE_REGISTERING_FLAG',
  UPDATE_ACTIVE_WELCOME_FORM: 'UPDATE_ACTIVE_WELCOME_FORM',

  UPDATE_REGISTERING_MESSAGE: 'UPDATE_REGISTERING_MESSAGE',
  UPDATE_LOGGING_IN_MESSAGE: 'UPDATE_LOGGING_IN_MESSAGE',
}